sistema:
  admin:
    login: ${ADM_LOGIN:user}
    senha: ${ADM_SENHA:123}

spring:
  application:
    name: report-generator
  datasource:
    url: ${URL_DATABASE:jdbc:postgresql://localhost:5432/generate-report}
    username: ${PROVEDOR_DATABASE:postgres}
    password: ${SENHA_DATABASE:Abc#123}
  jpa:
    hibernate:
      ddl-auto: validate